/* Auto-generated by bubble.py at 2026-06-25 16:30:19 */
window.BUBBLE_DATA = {
  "generated_at": "2026-06-25 16:30:19",
  "nikkei_close": 72366.34375,
  "nikkei_date": "2026-06-25",
  "auto_score": 75.4,
  "stage_num": 4,
  "stage_label": "吹き上げ期 (Blow-off Top)",
  "stage_color": "#f97316",
  "indicators": [
    {
      "key": "nikkei_vs_1989",
      "name": "日経 vs 1989 峰值 (38,915)",
      "display": "72,366 (+86.0%)",
      "score": 90.6,
      "reason": "心理位 · 历史唯一参照"
    },
    {
      "key": "monthly_rsi",
      "name": "日経 月線 RSI(14)",
      "display": "86.7",
      "score": 90.0,
      "reason": ">85 = 1989 同水準（当時 90+）"
    },
    {
      "key": "sma200_gap",
      "name": "日経 200日線乖離率",
      "display": "+33.7%",
      "score": 86.8,
      "reason": ">25% 加速段共通の警告"
    },
    {
      "key": "months_since",
      "name": "直近10%調整からの月数",
      "display": "6 ヶ月",
      "score": 40,
      "reason": ">18 ヶ月警戒 · 走得越久反弹越烈"
    },
    {
      "key": "vix",
      "name": "VIX (S&P 恐慌指数)",
      "display": "18.11",
      "score": 49.6,
      "reason": "<13 极度麻痺・翻车前夜"
    },
    {
      "key": "usdjpy",
      "name": "USD/JPY",
      "display": "¥161.81",
      "score": 84.4,
      "reason": ">155 carry trade 风险 · 2024-08 复刻"
    },
    {
      "key": "us_10y",
      "name": "US 10Y 国债利率",
      "display": "4.45%",
      "score": 73.8,
      "reason": ">4.5% 估值杀手"
    },
    {
      "key": "ytd",
      "name": "日経 2026年 YTD 涨幅",
      "display": "+39.6%",
      "score": 87.9,
      "reason": "1989 年 +29% 见顶"
    }
  ],
  "manual_checklist": [
    {
      "key": "taxi",
      "label": "出租车/美容師 開口推荐股票",
      "weight": 12
    },
    {
      "key": "family",
      "label": "同事・亲戚开始问股市",
      "weight": 10
    },
    {
      "key": "magazines",
      "label": "日経 4万・5万円大特集 媒体连发",
      "weight": 10
    },
    {
      "key": "nisa",
      "label": "新NISA 月间流入连续创新高",
      "weight": 8
    },
    {
      "key": "narrative",
      "label": "「今回は違う」「日本復活」论调流行",
      "weight": 10
    },
    {
      "key": "ipo",
      "label": "IPO 概念股暴炒・首日翻倍频繁",
      "weight": 10
    },
    {
      "key": "margin",
      "label": "信用買い残 屡创新高",
      "weight": 10
    },
    {
      "key": "boj",
      "label": "BOJ 加息 / 缩表加速",
      "weight": 10
    },
    {
      "key": "earnings",
      "label": "出口企业业绩开始下修",
      "weight": 10
    },
    {
      "key": "whale",
      "label": "大佬明显减仓（巴菲特・孙正义等）",
      "weight": 10
    }
  ]
};
