/* Auto-generated by credit.py at 2026-06-25 07:00:34 */
window.CREDIT_DATA = {
  "generated_at": "2026-06-25 07:00:34",
  "auto_score": 38.0,
  "stage_num": 2,
  "stage_label": "利差走阔 (Widening)",
  "stage_color": "#eab308",
  "stage_note": "开始示警·留意",
  "fred_ok": false,
  "thesis": "雷曼=信用·杠杆危机，非估值危机。别盯日経 PER 找顶，盯 AI 信用利差与 GPU 抵押贷款再融资——信用市场会先告诉你。",
  "transmission": "若引爆：路径同 2008 = 急速円高 + 出口利润蒸发。你的持仓(5803 フジクラ/5016 JX 等)处 AI capex 受益链下游——信用驱动的 capex 冻结会经①订单取消 ②円高 双重打击，故以 USD/JPY 急升作二次确认。",
  "indicators": [
    {
      "key": "hyg_lqd",
      "name": "HY/IG 相对强度 (HYG÷LQD)",
      "display": "距6月高点 -1.5%",
      "score": 15.9,
      "weight": 1.4,
      "reason": "比值下跌=高收益债跑输=信用利差走阔",
      "src": "Yahoo"
    },
    {
      "key": "move",
      "name": "MOVE 债市波动率",
      "display": "69.1",
      "score": 14.4,
      "weight": 1.2,
      "reason": "债市\"恐慌指数\"·信用应力直接读数",
      "src": "Yahoo"
    },
    {
      "key": "orcl",
      "name": "Oracle 回撤 (距52周高)",
      "display": "-52.0%  ($158)",
      "score": 77.2,
      "weight": 1.3,
      "reason": "循环融资/AI债务\"贝尔斯登候选\"·CDS已飙升",
      "src": "Yahoo"
    },
    {
      "key": "crwv",
      "name": "CoreWeave 回撤 (距52周高)",
      "display": "-38.9%  ($101)",
      "score": 62.4,
      "weight": 1.1,
      "reason": "GPU抵押贷款·11%利率·2026起还款碰上抵押品贬值",
      "src": "Yahoo"
    },
    {
      "key": "usdjpy_move",
      "name": "USD/JPY 近20日变动",
      "display": "+1.4%  (¥161.7)",
      "score": 19.3,
      "weight": 1.0,
      "reason": "急速円高=危机向日本传导(2008:107→90)·出口利润蒸发",
      "src": "Yahoo"
    }
  ],
  "manual_checklist": [
    {
      "key": "orcl_cds",
      "label": "Oracle 5Y CDS > 150bp（信用市场重定价）",
      "weight": 14,
      "link": "https://www.google.com/search?q=Oracle+5+year+CDS+spread"
    },
    {
      "key": "gpu_refi",
      "label": "GPU抵押贷款(CoreWeave类)再融资失败/利率飙升",
      "weight": 14,
      "link": "https://www.google.com/search?q=CoreWeave+debt+refinancing"
    },
    {
      "key": "pc_redeem",
      "label": "私募信贷基金 赎回冻结 / 大幅减记",
      "weight": 13,
      "link": "https://www.google.com/search?q=private+credit+fund+redemption+freeze+markdown"
    },
    {
      "key": "capex_gap",
      "label": "超大厂 capex 翻倍指引触发抛售(如 Alphabet)",
      "weight": 11,
      "link": "https://www.google.com/search?q=hyperscaler+capex+free+cash+flow+gap"
    },
    {
      "key": "circular",
      "label": "循环融资被揭示为\"圈内打转\"(Nvidia↔OpenAI↔CoreWeave)",
      "weight": 12,
      "link": "https://www.google.com/search?q=Nvidia+OpenAI+circular+financing"
    },
    {
      "key": "bank_expo",
      "label": "杠杆传导至储户银行体系(→升级为系统性)",
      "weight": 14,
      "link": "https://www.google.com/search?q=banks+exposure+AI+data+center+private+credit"
    },
    {
      "key": "jpy_spike",
      "label": "USD/JPY 单周急升 >5%(carry unwind 确认)",
      "weight": 10,
      "link": "https://finance.yahoo.com/quote/JPY=X"
    }
  ]
};
