#!/usr/bin/env python3
"""
AI硬件瓶颈雷达 · 行情抓取器

从 Yahoo Finance 抓取 data.js 里所有股票的最新收盘价 + 日涨跌，
写入 prices.js。HTML 用 <script src="prices.js"> 直接加载，没有 CORS 问题。

用法:
    python fetch_prices.py

输出: prices.js (会被 index.html 自动加载)
依赖: 仅标准库（urllib + json）
"""
import io
import json
import re
import sys
import time
from pathlib import Path
import urllib.request
import urllib.error

# 修正 Windows 控制台编码（cp932 / cp936 都救不了 ✓✗ 这种字符）
try:
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
    sys.stderr.reconfigure(encoding='utf-8', errors='replace')
except Exception:
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

ROOT = Path(__file__).parent
DATA_JS = ROOT / 'data.js'
OUT_JS = ROOT / 'prices.js'

UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36'


def parse_tickers():
    """从 data.js 提取唯一的 (ticker, name, market) 列表。"""
    text = DATA_JS.read_text(encoding='utf-8')
    pat = re.compile(
        r"\{\s*ticker\s*:\s*'([^']+)'\s*,\s*name\s*:\s*'([^']+)'\s*,\s*market\s*:\s*'([^']+)'"
    )
    seen = set()
    out = []
    for m in pat.finditer(text):
        t, n, mkt = m.group(1), m.group(2), m.group(3)
        if t == '-' or mkt == '未上市':
            continue
        if t in seen:
            continue
        seen.add(t)
        out.append({'ticker': t, 'name': n, 'market': mkt})
    return out


def fetch_one(ticker):
    """从 Yahoo Finance chart endpoint 抓取最近 5 天日线。返回最新收盘价/日期/日涨跌。"""
    url = (f'https://query1.finance.yahoo.com/v8/finance/chart/{ticker}'
           f'?interval=1d&range=5d')
    req = urllib.request.Request(url, headers={
        'User-Agent': UA,
        'Accept': 'application/json',
    })
    with urllib.request.urlopen(req, timeout=15) as r:
        raw = r.read().decode('utf-8', errors='ignore')
    data = json.loads(raw)
    result = data.get('chart', {}).get('result')
    if not result:
        err = data.get('chart', {}).get('error') or 'no result'
        raise ValueError(f'yahoo: {err}')
    r0 = result[0]
    meta = r0.get('meta', {})
    timestamps = r0.get('timestamp', [])
    quotes = r0.get('indicators', {}).get('quote', [{}])[0]
    closes = quotes.get('close', [])
    if not timestamps or not closes:
        raise ValueError('empty data')
    # 取最后一个非 None 的收盘价
    last_idx = None
    for i in range(len(closes) - 1, -1, -1):
        if closes[i] is not None:
            last_idx = i
            break
    if last_idx is None:
        raise ValueError('no valid close')
    prev_idx = None
    for i in range(last_idx - 1, -1, -1):
        if closes[i] is not None:
            prev_idx = i
            break
    last_close = closes[last_idx]
    prev_close = closes[prev_idx] if prev_idx is not None else None
    chg_pct = ((last_close - prev_close) / prev_close * 100) if prev_close else None
    date_str = time.strftime('%Y-%m-%d', time.localtime(timestamps[last_idx]))
    return {
        'close': last_close,
        'prevClose': prev_close,
        'date': date_str,
        'chgPct': chg_pct,
        'currency': meta.get('currency'),
    }


def main():
    items = parse_tickers()
    print(f'[fetch_prices] {len(items)} tickers extracted from data.js', flush=True)
    results = {}
    ok = fail = 0
    for i, it in enumerate(items, 1):
        t = it['ticker']
        try:
            d = fetch_one(t)
            results[t] = {
                'close': d['close'],
                'prevClose': d['prevClose'],
                'date': d['date'],
                'chgPct': d['chgPct'],
                'currency': d['currency'],
                'fetchedAt': int(time.time() * 1000),
                'name': it['name'],
                'market': it['market'],
            }
            ok += 1
            chg_str = f' ({d["chgPct"]:+.2f}%)' if d['chgPct'] is not None else ''
            print(f'  [{i:2d}/{len(items)}] {t:12s} OK  {d["close"]:>10}{chg_str}  {d["date"]}', flush=True)
        except Exception as e:
            results[t] = {
                'err': str(e)[:80],
                'fetchedAt': int(time.time() * 1000),
                'name': it['name'],
                'market': it['market'],
            }
            fail += 1
            print(f'  [{i:2d}/{len(items)}] {t:12s} FAIL  {e}', flush=True)
        time.sleep(0.2)

    stamp = time.strftime('%Y-%m-%d %H:%M:%S')
    js = (
        f'/* Auto-generated by fetch_prices.py at {stamp} */\n'
        f'window.PRICES_DATA = {json.dumps(results, ensure_ascii=False, indent=2)};\n'
        f'window.PRICES_GENERATED_AT = "{stamp}";\n'
    )
    OUT_JS.write_text(js, encoding='utf-8')
    print(f'\n[fetch_prices] Done: {ok} ok / {fail} fail -> {OUT_JS.name}', flush=True)
    return 0 if ok > 0 else 1


if __name__ == '__main__':
    sys.exit(main())
