/* Auto-generated by fetch_prices.py at 2026-06-26 07:00:16 */
window.PRICES_DATA = {
  "4063.T": {
    "close": 7150.0,
    "prevClose": 7100.0,
    "date": "2026-06-25",
    "chgPct": 0.7042253521126761,
    "currency": "JPY",
    "fetchedAt": 1782424803748,
    "name": "信越化学工業",
    "market": "日股"
  },
  "3436.T": {
    "close": 3794.0,
    "prevClose": 3711.0,
    "date": "2026-06-25",
    "chgPct": 2.236593909997305,
    "currency": "JPY",
    "fetchedAt": 1782424804107,
    "name": "SUMCO",
    "market": "日股"
  },
  "6857.T": {
    "close": 35900.0,
    "prevClose": 31200.0,
    "date": "2026-06-25",
    "chgPct": 15.064102564102564,
    "currency": "JPY",
    "fetchedAt": 1782424804529,
    "name": "アドバンテスト",
    "market": "日股"
  },
  "000660.KS": {
    "close": 2917000.0,
    "prevClose": 2621000.0,
    "date": "2026-06-25",
    "chgPct": 11.293399465852728,
    "currency": "KRW",
    "fetchedAt": 1782424804983,
    "name": "SK Hynix",
    "market": "韩股"
  },
  "MU": {
    "close": 1213.56005859375,
    "prevClose": 1048.510009765625,
    "date": "2026-06-25",
    "chgPct": 15.741389904805859,
    "currency": "USD",
    "fetchedAt": 1782424805376,
    "name": "Micron",
    "market": "美股"
  },
  "5803.T": {
    "close": 6436.0,
    "prevClose": 6313.0,
    "date": "2026-06-25",
    "chgPct": 1.9483605258989387,
    "currency": "JPY",
    "fetchedAt": 1782424805834,
    "name": "フジクラ",
    "market": "日股"
  },
  "4062.T": {
    "close": 26370.0,
    "prevClose": 24785.0,
    "date": "2026-06-25",
    "chgPct": 6.394996973976196,
    "currency": "JPY",
    "fetchedAt": 1782424806300,
    "name": "イビデン",
    "market": "日股"
  },
  "AVGO": {
    "close": 378.9100036621094,
    "prevClose": 382.07000732421875,
    "date": "2026-06-25",
    "chgPct": -0.8270745155423426,
    "currency": "USD",
    "fetchedAt": 1782424806735,
    "name": "Broadcom",
    "market": "美股"
  },
  "NVDA": {
    "close": 195.74000549316406,
    "prevClose": 199.0,
    "date": "2026-06-25",
    "chgPct": -1.6381881943899181,
    "currency": "USD",
    "fetchedAt": 1782424807077,
    "name": "NVIDIA",
    "market": "美股"
  },
  "COHR": {
    "close": 407.25,
    "prevClose": 392.5,
    "date": "2026-06-25",
    "chgPct": 3.7579617834394905,
    "currency": "USD",
    "fetchedAt": 1782424807474,
    "name": "Coherent",
    "market": "美股"
  },
  "7735.T": {
    "close": 17625.0,
    "prevClose": 16130.0,
    "date": "2026-06-25",
    "chgPct": 9.268443893366397,
    "currency": "JPY",
    "fetchedAt": 1782424807937,
    "name": "SCREEN HD",
    "market": "日股"
  },
  "6146.T": {
    "close": 85970.0,
    "prevClose": 79740.0,
    "date": "2026-06-25",
    "chgPct": 7.812891898670679,
    "currency": "JPY",
    "fetchedAt": 1782424808354,
    "name": "ディスコ",
    "market": "日股"
  },
  "TSM": {
    "close": 434.989990234375,
    "prevClose": 440.8299865722656,
    "date": "2026-06-25",
    "chgPct": -1.324772931918793,
    "currency": "USD",
    "fetchedAt": 1782424808810,
    "name": "TSMC",
    "market": "美股"
  },
  "7741.T": {
    "close": 26120.0,
    "prevClose": 26350.0,
    "date": "2026-06-25",
    "chgPct": -0.8728652751423149,
    "currency": "JPY",
    "fetchedAt": 1782424809295,
    "name": "HOYA",
    "market": "日股"
  },
  "6971.T": {
    "close": 3558.0,
    "prevClose": 3517.0,
    "date": "2026-06-25",
    "chgPct": 1.1657662780779072,
    "currency": "JPY",
    "fetchedAt": 1782424809720,
    "name": "京セラ",
    "market": "日股"
  },
  "INTC": {
    "close": 132.8699951171875,
    "prevClose": 131.64999389648438,
    "date": "2026-06-25",
    "chgPct": 0.9267005524226647,
    "currency": "USD",
    "fetchedAt": 1782424810249,
    "name": "Intel",
    "market": "美股"
  },
  "5016.T": {
    "close": 4887.0,
    "prevClose": 4633.0,
    "date": "2026-06-25",
    "chgPct": 5.482408806388949,
    "currency": "JPY",
    "fetchedAt": 1782424810680,
    "name": "JX Advanced Metals",
    "market": "日股"
  },
  "5713.T": {
    "close": 7653.0,
    "prevClose": 7955.0,
    "date": "2026-06-25",
    "chgPct": -3.7963544940289125,
    "currency": "JPY",
    "fetchedAt": 1782424811311,
    "name": "住友金属鉱山",
    "market": "日股"
  },
  "6504.T": {
    "close": 14290.0,
    "prevClose": 14690.0,
    "date": "2026-06-25",
    "chgPct": -2.722940776038121,
    "currency": "JPY",
    "fetchedAt": 1782424811828,
    "name": "富士電機",
    "market": "日股"
  },
  "6890.T": {
    "close": 10260.0,
    "prevClose": 9800.0,
    "date": "2026-06-25",
    "chgPct": 4.6938775510204085,
    "currency": "JPY",
    "fetchedAt": 1782424812294,
    "name": "Ferrotec HD",
    "market": "日股"
  },
  "6594.T": {
    "close": 2654.0,
    "prevClose": 2750.0,
    "date": "2026-06-25",
    "chgPct": -3.490909090909091,
    "currency": "JPY",
    "fetchedAt": 1782424812797,
    "name": "ニデック",
    "market": "日股"
  },
  "6503.T": {
    "close": 5986.0,
    "prevClose": 5982.0,
    "date": "2026-06-25",
    "chgPct": 0.06686726847208291,
    "currency": "JPY",
    "fetchedAt": 1782424813452,
    "name": "三菱電機",
    "market": "日股"
  },
  "VRT": {
    "close": 325.57000732421875,
    "prevClose": 316.42999267578125,
    "date": "2026-06-25",
    "chgPct": 2.888479240273058,
    "currency": "USD",
    "fetchedAt": 1782424813841,
    "name": "Vertiv",
    "market": "美股"
  },
  "6367.T": {
    "close": 23850.0,
    "prevClose": 23490.0,
    "date": "2026-06-25",
    "chgPct": 1.532567049808429,
    "currency": "JPY",
    "fetchedAt": 1782424814312,
    "name": "ダイキン工業",
    "market": "日股"
  },
  "6845.T": {
    "close": 1717.5,
    "prevClose": 1691.5,
    "date": "2026-06-25",
    "chgPct": 1.537097250960686,
    "currency": "JPY",
    "fetchedAt": 1782424814749,
    "name": "アズビル",
    "market": "日股"
  },
  "IBM": {
    "close": 258.2699890136719,
    "prevClose": 262.9599914550781,
    "date": "2026-06-25",
    "chgPct": -1.7835422093887048,
    "currency": "USD",
    "fetchedAt": 1782424815219,
    "name": "IBM",
    "market": "美股"
  },
  "BRCHF": {
    "close": 0.10999999940395355,
    "prevClose": 0.12300000339746475,
    "date": "2026-06-24",
    "chgPct": -10.56910864587761,
    "currency": "USD",
    "fetchedAt": 1782424815676,
    "name": "BrainChip",
    "market": "OTC"
  },
  "IONQ": {
    "close": 50.560001373291016,
    "prevClose": 53.599998474121094,
    "date": "2026-06-25",
    "chgPct": -5.671636543605193,
    "currency": "USD",
    "fetchedAt": 1782424816118,
    "name": "IonQ",
    "market": "美股"
  },
  "6702.T": {
    "close": 3187.0,
    "prevClose": 3232.0,
    "date": "2026-06-25",
    "chgPct": -1.3923267326732673,
    "currency": "JPY",
    "fetchedAt": 1782424816702,
    "name": "富士通",
    "market": "日股"
  }
};
window.PRICES_GENERATED_AT = "2026-06-26 07:00:16";
