/* Auto-generated by fetch_prices.py at 2026-07-02 07:00:15 */
window.PRICES_DATA = {
  "4063.T": {
    "close": 7259.0,
    "prevClose": 7008.0,
    "date": "2026-07-01",
    "chgPct": 3.58162100456621,
    "currency": "JPY",
    "fetchedAt": 1782943204337,
    "name": "信越化学工業",
    "market": "日股"
  },
  "3436.T": {
    "close": 4729.0,
    "prevClose": 4029.0,
    "date": "2026-07-01",
    "chgPct": 17.374038222884092,
    "currency": "JPY",
    "fetchedAt": 1782943204744,
    "name": "SUMCO",
    "market": "日股"
  },
  "6857.T": {
    "close": 32000.0,
    "prevClose": 32340.0,
    "date": "2026-07-01",
    "chgPct": -1.051329622758194,
    "currency": "JPY",
    "fetchedAt": 1782943205135,
    "name": "アドバンテスト",
    "market": "日股"
  },
  "000660.KS": {
    "close": 2560000.0,
    "prevClose": 2650000.0,
    "date": "2026-07-01",
    "chgPct": -3.3962264150943398,
    "currency": "KRW",
    "fetchedAt": 1782943205509,
    "name": "SK Hynix",
    "market": "韩股"
  },
  "MU": {
    "close": 1032.280029296875,
    "prevClose": 1154.2900390625,
    "date": "2026-07-01",
    "chgPct": -10.570134510102852,
    "currency": "USD",
    "fetchedAt": 1782943205917,
    "name": "Micron",
    "market": "美股"
  },
  "5803.T": {
    "close": 5826.0,
    "prevClose": 6238.0,
    "date": "2026-07-01",
    "chgPct": -6.604680987495993,
    "currency": "JPY",
    "fetchedAt": 1782943206306,
    "name": "フジクラ",
    "market": "日股"
  },
  "4062.T": {
    "close": 25785.0,
    "prevClose": 23815.0,
    "date": "2026-07-01",
    "chgPct": 8.272097417593953,
    "currency": "JPY",
    "fetchedAt": 1782943206744,
    "name": "イビデン",
    "market": "日股"
  },
  "AVGO": {
    "close": 369.3399963378906,
    "prevClose": 377.75,
    "date": "2026-07-01",
    "chgPct": -2.2263411415246526,
    "currency": "USD",
    "fetchedAt": 1782943207072,
    "name": "Broadcom",
    "market": "美股"
  },
  "NVDA": {
    "close": 197.5800018310547,
    "prevClose": 200.08999633789062,
    "date": "2026-07-01",
    "chgPct": -1.254432781635583,
    "currency": "USD",
    "fetchedAt": 1782943207336,
    "name": "NVIDIA",
    "market": "美股"
  },
  "COHR": {
    "close": 368.6499938964844,
    "prevClose": 394.4700012207031,
    "date": "2026-07-01",
    "chgPct": -6.545493255334425,
    "currency": "USD",
    "fetchedAt": 1782943207672,
    "name": "Coherent",
    "market": "美股"
  },
  "7735.T": {
    "close": 19490.0,
    "prevClose": 17805.0,
    "date": "2026-07-01",
    "chgPct": 9.463633810727323,
    "currency": "JPY",
    "fetchedAt": 1782943208080,
    "name": "SCREEN HD",
    "market": "日股"
  },
  "6146.T": {
    "close": 84520.0,
    "prevClose": 81260.0,
    "date": "2026-07-01",
    "chgPct": 4.011813930593157,
    "currency": "JPY",
    "fetchedAt": 1782943208556,
    "name": "ディスコ",
    "market": "日股"
  },
  "TSM": {
    "close": 444.2300109863281,
    "prevClose": 477.57000732421875,
    "date": "2026-07-01",
    "chgPct": -6.98117466058884,
    "currency": "USD",
    "fetchedAt": 1782943208829,
    "name": "TSMC",
    "market": "美股"
  },
  "7741.T": {
    "close": 25905.0,
    "prevClose": 25950.0,
    "date": "2026-07-01",
    "chgPct": -0.17341040462427745,
    "currency": "JPY",
    "fetchedAt": 1782943209212,
    "name": "HOYA",
    "market": "日股"
  },
  "6971.T": {
    "close": 3821.0,
    "prevClose": 3561.0,
    "date": "2026-07-01",
    "chgPct": 7.301319853973603,
    "currency": "JPY",
    "fetchedAt": 1782943209604,
    "name": "京セラ",
    "market": "日股"
  },
  "INTC": {
    "close": 127.0199966430664,
    "prevClose": 139.6300048828125,
    "date": "2026-07-01",
    "chgPct": -9.031016113140808,
    "currency": "USD",
    "fetchedAt": 1782943210004,
    "name": "Intel",
    "market": "美股"
  },
  "5016.T": {
    "close": 4219.0,
    "prevClose": 4398.0,
    "date": "2026-07-01",
    "chgPct": -4.070031832651205,
    "currency": "JPY",
    "fetchedAt": 1782943210358,
    "name": "JX Advanced Metals",
    "market": "日股"
  },
  "5713.T": {
    "close": 7336.0,
    "prevClose": 7469.0,
    "date": "2026-07-01",
    "chgPct": -1.7806935332708531,
    "currency": "JPY",
    "fetchedAt": 1782943210743,
    "name": "住友金属鉱山",
    "market": "日股"
  },
  "6504.T": {
    "close": 14095.0,
    "prevClose": 13515.0,
    "date": "2026-07-01",
    "chgPct": 4.2915279319274875,
    "currency": "JPY",
    "fetchedAt": 1782943211148,
    "name": "富士電機",
    "market": "日股"
  },
  "6890.T": {
    "close": 9720.0,
    "prevClose": 9530.0,
    "date": "2026-07-01",
    "chgPct": 1.993704092339979,
    "currency": "JPY",
    "fetchedAt": 1782943211508,
    "name": "Ferrotec HD",
    "market": "日股"
  },
  "6594.T": {
    "close": 2747.0,
    "prevClose": 2645.0,
    "date": "2026-07-01",
    "chgPct": 3.856332703213611,
    "currency": "JPY",
    "fetchedAt": 1782943211869,
    "name": "ニデック",
    "market": "日股"
  },
  "6503.T": {
    "close": 6034.0,
    "prevClose": 5876.0,
    "date": "2026-07-01",
    "chgPct": 2.6889040163376445,
    "currency": "JPY",
    "fetchedAt": 1782943212275,
    "name": "三菱電機",
    "market": "日股"
  },
  "VRT": {
    "close": 311.4200134277344,
    "prevClose": 334.82000732421875,
    "date": "2026-07-01",
    "chgPct": -6.988827843201522,
    "currency": "USD",
    "fetchedAt": 1782943212634,
    "name": "Vertiv",
    "market": "美股"
  },
  "6367.T": {
    "close": 24795.0,
    "prevClose": 24685.0,
    "date": "2026-07-01",
    "chgPct": 0.4456147457970428,
    "currency": "JPY",
    "fetchedAt": 1782943213034,
    "name": "ダイキン工業",
    "market": "日股"
  },
  "6845.T": {
    "close": 1712.5,
    "prevClose": 1719.5,
    "date": "2026-07-01",
    "chgPct": -0.40709508578075027,
    "currency": "JPY",
    "fetchedAt": 1782943213432,
    "name": "アズビル",
    "market": "日股"
  },
  "IBM": {
    "close": 286.25,
    "prevClose": 281.2099914550781,
    "date": "2026-07-01",
    "chgPct": 1.7922579915610823,
    "currency": "USD",
    "fetchedAt": 1782943213881,
    "name": "IBM",
    "market": "美股"
  },
  "BRCHF": {
    "close": 0.11699999868869781,
    "prevClose": 0.1120000034570694,
    "date": "2026-07-01",
    "chgPct": 4.464281319013495,
    "currency": "USD",
    "fetchedAt": 1782943214213,
    "name": "BrainChip",
    "market": "OTC"
  },
  "IONQ": {
    "close": 51.400001525878906,
    "prevClose": 53.2599983215332,
    "date": "2026-07-01",
    "chgPct": -3.4922960087707953,
    "currency": "USD",
    "fetchedAt": 1782943214568,
    "name": "IonQ",
    "market": "美股"
  },
  "6702.T": {
    "close": 3237.0,
    "prevClose": 3247.0,
    "date": "2026-07-01",
    "chgPct": -0.3079765937788728,
    "currency": "JPY",
    "fetchedAt": 1782943214947,
    "name": "富士通",
    "market": "日股"
  }
};
window.PRICES_GENERATED_AT = "2026-07-02 07:00:15";
